### ISSUE TITLE
error : XHOOK-WoW-1.12.1-master\xhookwow\xhookwow.vcxproj" could not be found.

### ISSUE THREAD

**Issue by m0use0ver** [maikel233/XHOOK-WoW-1.12.1#1]
when i inject the file and a console opens up, it says "could not find return adress" and fails to load further.

i am trying to use the hook on elysium(nightheaven), 1.12
it would also be helpful for my learning to be able to look into the project.. however, as you see i cannot even load it :/

**Comment by maikel233** [comment]
> when i inject the file and a console opens up, it says "could not find return adress" and fails to load further.
> 
> i am trying to use the hook on elysium(nightheaven), 1.12
> it would also be helpful for my learning to be able to look into the project.. however, as you see i cannot even load it :/

You can download the source if you want just uploaded it.
If you want to fix the no return issue you have to change the d3d9 hooking method.
